name: PSRC Data Stories
description: Making meaning from urban planning data
url: http://psrc.github.io
lsi: false
kramdown:
  input: GFM
timezone: America/Los_Angeles
permalink: /:categories/:year/:title
gems:
  - jekyll-sitemap
